import { blue, green, red, yellow } from '@tamagui/colors';

// Light mode palette (default)
const lightPalette = {
  background: '#FFFFFF',
  backgroundHover: '#F9FAFB',
  backgroundPress: '#F3F4F6',
  color: '#022C22',
  colorHover: '#111827',
  colorPress: '#052E16',
  colorFocus: '#022C22',
  colorTransparent: 'rgba(2,44,34,0)',
  borderColor: '#E5E7EB',
  borderColorHover: '#D1D5DB',
  borderColorFocus: 'hsla(175, 66%, 46%, 1)',
  shadowColor: 'rgba(0,0,0,0.06)',
  colorMuted: '#64748B',
};

// Dark mode palette
const darkPalette = {
  background: '#0A0A0A',
  backgroundHover: '#141414',
  backgroundPress: '#1A1A1A',
  color: '#F2F5F7',
  colorHover: '#EEF2F6',
  colorPress: '#E6EBF0',
  colorFocus: '#F2F5F7',
  colorTransparent: 'rgba(250,250,250,0)',
  borderColor: '#262626',
  borderColorHover: '#404040',
  borderColorFocus: 'hsla(175, 66%, 46%, 1)',
  shadowColor: 'rgba(0,0,0,0.3)',
  colorMuted: '#98A4B3',
};

const accentBrand = {
  accent1: 'hsla(175, 72%, 36%, 1)',
  accent3: 'hsla(175, 68%, 42%, 1)',
  accent4: 'hsla(175, 66%, 46%, 1)',
};

const accentBrandDark = {
  accent1: 'hsla(175, 72%, 45%, 1)',
  accent3: 'hsla(175, 68%, 50%, 1)',
  accent4: 'hsla(175, 66%, 55%, 1)',
};

const accentBrandAlpha = {
  pillBgLight: 'hsla(175, 66%, 46%, 0.12)',
  pillBgDark: 'hsla(175, 66%, 46%, 0.20)',
  focusRing: 'hsla(175, 66%, 46%, 0.3)',
};

export const themes = {
  brand: {
    ...lightPalette,
    white: '#FFFFFF',
    red10: red.red10,
    primary: accentBrand.accent4,
    accent: accentBrand.accent4,
    error: red.red10,
    brandPrimary: accentBrand.accent4,
    brandPrimarySoft: accentBrand.accent3,
    brandAccent: yellow.yellow9,
    brandAccentSoft: yellow.yellow3,
    surface: '#FFFFFF',
    surfaceSubtle: '#F9FAFB',
    surfaceElevated: '#FFFFFF',
    surfaceBorder: '#E5E7EB',
    success: green.green9,
    successSoft: green.green3,
    warning: yellow.yellow9,
    warningSoft: yellow.yellow3,
    danger: red.red10,
    dangerSoft: red.red3,
    headerBackground: accentBrand.accent1,
    colorSubtle: '#4B5563',
    colorMuted: '#64748B',
    tabBarInactive: '#4B5563',
    tabBarPillBackground: accentBrandAlpha.pillBgLight,
    placeholderColor: '#6B7280',
    colorDisabled: '#9CA3AF',
    backgroundDisabled: '#F3F4F6',
    borderColorDisabled: '#E5E7EB',
    outlineColor: accentBrandAlpha.focusRing,
    backgroundFocus: '#FFFFFF',
    info: blue.blue9,
    infoSoft: blue.blue3,
    sheetOverlay: 'rgba(0,0,0,0.4)',
  },
  brand_dark: {
    ...darkPalette,
    white: '#0A0A0A',
    red10: red.red5,
    primary: accentBrandDark.accent4,
    accent: accentBrandDark.accent4,
    error: '#FF8F8F',
    brandPrimary: accentBrandDark.accent4,
    brandPrimarySoft: accentBrandDark.accent3,
    brandAccent: yellow.yellow5,
    brandAccentSoft: yellow.yellow1,
    surface: '#141414',
    surfaceSubtle: '#1A1A1A',
    surfaceElevated: '#262626',
    surfaceBorder: '#404040',
    success: green.green5,
    successSoft: green.green1,
    warning: yellow.yellow5,
    warningSoft: yellow.yellow1,
    danger: '#FF8F8F',
    dangerSoft: red.red1,
    headerBackground: accentBrandDark.accent1,
    colorSubtle: '#AAB4C2',
    colorMuted: '#98A4B3',
    tabBarInactive: '#AAB4C2',
    tabBarPillBackground: accentBrandAlpha.pillBgDark,
    placeholderColor: '#98A4B3',
    colorDisabled: '#8A94A3',
    backgroundDisabled: '#262626',
    borderColorDisabled: '#404040',
    outlineColor: accentBrandAlpha.focusRing,
    backgroundFocus: '#1A1A1A',
    info: blue.blue5,
    infoSoft: blue.blue1,
    sheetOverlay: 'rgba(0,0,0,0.6)',
  },
} as const;

export type Themes = typeof themes;

export const DEFAULT_THEME_VALUES = {
  background: '#FFFFFF',
  surface: '#FFFFFF',
  surfaceElevated: '#FFFFFF',
  borderColor: '#E5E7EB',
  color: '#022C22',
  colorPress: '#052E16',
  colorSubtle: '#4B5563',
  primary: accentBrand.accent4,
  brandPrimary: accentBrand.accent4,
  shadowColor: 'rgba(0,0,0,0.06)',
  white: '#FFFFFF',
  placeholderColor: '#6B7280',
  colorDisabled: '#9CA3AF',
  backgroundDisabled: '#F3F4F6',
  borderColorDisabled: '#E5E7EB',
  outlineColor: accentBrandAlpha.focusRing,
  backgroundFocus: '#FFFFFF',
  borderColorFocus: accentBrand.accent4,
  danger: red.red10,
  info: blue.blue9,
  infoSoft: blue.blue3,
  tabBarPillBackground: accentBrandAlpha.pillBgLight,
  tabBarInactive: '#4B5563',
} as const;
